using AuthServer.Database;
using AuthServer.DependencyInjection;
using AuthServer.Authentication;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi;
using System.Security.Claims;
using System.Text;
using System.Threading.RateLimiting;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

IConfigurationSection jwtSettings = builder.Configuration.GetSection("Jwt");
string signingKey = GetJwtSetting(jwtSettings, "AuthServiceKey", "JWT signing key");
string issuer = GetJwtSetting(jwtSettings, "Issuer", "JWT issuer");
string audience = GetJwtSetting(jwtSettings, "Audience", "JWT audience");

builder.Services.AddDbContext<AuthContext>(options =>
                options.UseSqlServer(builder.Configuration["ConnectionStrings:Default"]),
                ServiceLifetime.Scoped);

builder.Services.AddMemoryCache();
builder.Services.AddRateLimiter(options =>
{
    int authenticationPermitLimit = builder.Configuration.GetValue("RateLimiting:Authentication:PermitLimit", 100);
    TimeSpan authenticationWindow = TimeSpan.FromSeconds(
        builder.Configuration.GetValue("RateLimiting:Authentication:WindowSeconds", 60));

    options.AddPolicy("Authentication", httpContext =>
        RateLimitPartition.GetFixedWindowLimiter(
            partitionKey: httpContext.Connection.RemoteIpAddress?.ToString() ?? "unknown",
            factory: _ => new FixedWindowRateLimiterOptions
            {
                PermitLimit = authenticationPermitLimit,
                Window = authenticationWindow,
                QueueLimit = 0
            }));
});

builder.Services.AddComponentsFromAssemblyContaining<Program>();
builder.Services.AddMediatR(configuration => configuration.RegisterServicesFromAssemblyContaining<Program>());

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new()
        {
            ValidateIssuer = true,
            ValidIssuer = issuer,
            ValidateAudience = true,
            ValidAudience = audience,
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(signingKey)),
            ValidateLifetime = true,
            ClockSkew = TimeSpan.FromMinutes(1)
        };

        options.Events = new JwtBearerEvents
        {
            OnMessageReceived = context =>
            {
                if (string.IsNullOrWhiteSpace(context.Token)
                    && context.Request.Cookies.TryGetValue(AuthenticationCookieNames.AccessToken, out string? accessToken))
                {
                    context.Token = accessToken;
                }

                return Task.CompletedTask;
            },
            OnTokenValidated = async context =>
            {
                string? userIdValue = context.Principal?.FindFirstValue(ClaimTypes.NameIdentifier);
                string? sessionVersionValue = context.Principal?.FindFirstValue("session_version");

                if (!Guid.TryParse(userIdValue, out Guid userId)
                    || !int.TryParse(sessionVersionValue, out int tokenSessionVersion))
                {
                    context.Fail("Invalid token.");
                    return;
                }

                AuthContext authContext = context.HttpContext.RequestServices.GetRequiredService<AuthContext>();
                int? currentSessionVersion = await authContext.Users
                    .Where(user => user.Id == userId)
                    .Select(user => (int?)user.SessionVersion)
                    .FirstOrDefaultAsync(context.HttpContext.RequestAborted)
                    .ConfigureAwait(false);

                if (currentSessionVersion is null || currentSessionVersion.Value != tokenSessionVersion)
                {
                    context.Fail("Token has been revoked.");
                }
            }
        };
    });

builder.Services.AddAuthorizationBuilder()
    .AddPolicy("FullPrivilege", policy => policy.RequireClaim("privilege", "Full"));

builder.Services.AddControllers(options =>
{
    options.Filters.Add<LoginLockoutFilter>();
});
// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();
builder.Services.AddSwaggerGen(options =>
{
    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT",
        Description = "Paste JWT token generated by /api/auth/sign-in."
    });

    options.AddSecurityRequirement(document => new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecuritySchemeReference("Bearer", document),
            []
        }
    });
});

var app = builder.Build();

using (IServiceScope scope = app.Services.CreateScope())
{
    AuthContext authContext = scope.ServiceProvider.GetRequiredService<AuthContext>();
    await authContext.Database.MigrateAsync();
    await DatabaseSeeder.SeedAsync(authContext, app.Configuration);
}

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseRateLimiter();
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();

static string GetJwtSetting(IConfigurationSection jwtSettings, string key, string settingName)
{
    string? value = jwtSettings[key]
        ?? Environment.GetEnvironmentVariable($"Jwt__{key}")
        ?? Environment.GetEnvironmentVariable($"JWT__{key.ToUpperInvariant()}");

    if (string.IsNullOrWhiteSpace(value))
    {
        throw new InvalidOperationException(
            $"{settingName} is not configured. Please set Jwt:{key} in configuration or Jwt__{key} in environment variables.");
    }

    return value;
}
