using AuthServer.Authentication;
using AuthServer.Database;
using AuthServer.Database.Repositories;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi;
using System.Security.Claims;
using System.Text;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

IConfigurationSection jwtSettings = builder.Configuration.GetSection("Jwt");
string? signingKey = jwtSettings["AuthServiceKey"];
if (string.IsNullOrWhiteSpace(signingKey))
{
    throw new InvalidOperationException("JWT signing key is not configured. Please set Jwt:AuthServiceKey in configuration or environment variables.");
}

string issuer = jwtSettings["Issuer"] ?? throw new InvalidOperationException("JWT issuer is not configured.");
string audience = jwtSettings["Audience"] ?? throw new InvalidOperationException("JWT audience is not configured.");

builder.Services.AddDbContext<AuthContext>(options => 
                options.UseSqlServer(builder.Configuration["ConnectionStrings:Default"]),
                ServiceLifetime.Scoped);


builder.Services.AddScoped<IPrivilegeRepository, PrivilegeRepository>();
builder.Services.AddScoped<IRoleRepository, RoleRepository>();
builder.Services.AddScoped<IUserRepository, UserRepository>();
builder.Services.AddScoped<JwtTokenService>();
builder.Services.AddScoped<RefreshTokenService>();
builder.Services.AddMediatR(configuration => configuration.RegisterServicesFromAssemblyContaining<Program>());

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new()
        {
            ValidateIssuer = true,
            ValidIssuer = issuer,
            ValidateAudience = true,
            ValidAudience = audience,
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(signingKey)),
            ValidateLifetime = true,
            ClockSkew = TimeSpan.FromMinutes(1)
        };

        options.Events = new JwtBearerEvents
        {
            OnTokenValidated = async context =>
            {
                string? userIdValue = context.Principal?.FindFirstValue(ClaimTypes.NameIdentifier);
                string? sessionVersionValue = context.Principal?.FindFirstValue("session_version");

                if (!Guid.TryParse(userIdValue, out Guid userId)
                    || !int.TryParse(sessionVersionValue, out int tokenSessionVersion))
                {
                    context.Fail("Invalid token.");
                    return;
                }

                AuthContext authContext = context.HttpContext.RequestServices.GetRequiredService<AuthContext>();
                int? currentSessionVersion = await authContext.Users
                    .Where(user => user.Id == userId)
                    .Select(user => (int?)user.SessionVersion)
                    .FirstOrDefaultAsync(context.HttpContext.RequestAborted)
                    .ConfigureAwait(false);

                if (currentSessionVersion is null || currentSessionVersion.Value != tokenSessionVersion)
                {
                    context.Fail("Token has been revoked.");
                }
            }
        };
    });

builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("FullPrivilege", policy => policy.RequireClaim("privilege", "Full"));
});

builder.Services.AddControllers();
// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();
builder.Services.AddSwaggerGen(options =>
{
    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT",
        Description = "Paste JWT token generated by /api/auth/sign-in."
    });

    options.AddSecurityRequirement(document => new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecuritySchemeReference("Bearer", document),
            []
        }
    });
});

var app = builder.Build();

using (IServiceScope scope = app.Services.CreateScope())
{
    AuthContext authContext = scope.ServiceProvider.GetRequiredService<AuthContext>();
    await authContext.Database.MigrateAsync();
    await DatabaseSeeder.SeedAsync(authContext);
}

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();
